apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    app: vprodb
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /dbvolume
